### ISSUE TITLE
Fix the styling on the menu item link

### ISSUE THREAD

**Issue by ayleeandersen** [ServiceNowDevProgram/Menu-Generating-Operations-Program-Widget-Custom-Component#21]
In "You & I Builder Live!", we changed the menu item link so that it displays the dropdown when `editMode === true` and plain text when false. However, we weren't able to finish getting the label displayed instead of the id. To resolve this issue, please fine tune the changes we made to menu-item.js so that the "External Link" or "Internal Link" is displayed instead of their id values. Also make it look somewhat decent 😉 

"You & I Builder Live!" episode for reference: https://www.youtube.com/watch?v=kiT_9OGvX5A

**Comment by Lacah** [comment]
Resolved by PR #22
